apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-git-autosync
  labels:
    app: test-git-autosync
spec:
  selector:
    matchLabels:
      app: test-git-autosync
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-git-autosync
    spec:
      volumes:
        - name: sync
          emptyDir: {}
      initContainers:
        - name: autosync-clone
          image: lamaani/git_autosync
          volumeMounts:
            - mountPath: /sync
              name: sync
          env:
            - name: GIT_AUTOSYNC_REPO_LOCAL_PATH
              value: /sync
            - name: GIT_AUTOSYNC_MAX_SYNC_RUN_COUNT
              value: "0"
      containers:
        - name: website
          image: halverneus/static-file-server
          volumeMounts:
            - mountPath: /sync
              name: sync
          env:
            - name: FOLDER
              value: /sync/examples/website
            - name: DEBUG
              value: "true"
            - name: SHOW_LISTING
              value: "true"
          ports:
            - containerPort: 8080
          # The git_autosync sidecar
        - name: autosync
          image: lamaani/git_autosync
          volumeMounts:
            - mountPath: /sync
              name: sync
          env:
            - name: GIT_AUTOSYNC_REPO_LOCAL_PATH
              value: /sync
---
apiVersion: v1
kind: Service
metadata:
  name: test-git-autosync-svc
spec:
  selector:
    app: test-git-autosync
  type: LoadBalancer
  ports:
    - name: website
      port: 8080
